name: dev
channels:
- conda-forge
- pytorch
dependencies:
- numpy
- scipy
- numba
- cudatoolkit=11.0
- pytorch
- torchvision
- torchaudio
- opt_einsum
- python=3.7
- matplotlib
- jupyterlab
- nodejs
- pip
- pip:
  - sparse
  - ray[all]
  - line_profiler
  - memory_profiler

