name: dev
channels:
- pytorch
- conda-forge
dependencies:
- cmake
- sympy
- numpy
- scipy
- numba
- cudatoolkit=11.0
- pytorch
- torchaudio
- torchvision
- torchaudio
- opt_einsum
- python=3.7
- matplotlib
- jupyterlab=2.*
- nodejs
- pip
- pip:
  - sparse
  - ray[all]
  - cirq
  - qsimcirq
  - cirq[contrib]
  - tensorflow
  - tensorflow-quantum
  - line_profiler
  - memory_profiler
  - jupyterlab-nvdashboard
